### PR TITLE
Add support for keybase

### LINKED ISSUE #97: Add keybase.io
http://keybase.io provides verified links to other identities, so it is a good account to have registered early.

### PR DESCRIPTION
**Pull request by seeeturtle**
I refered to https://github.com/keybase/keybase-issues/issues/757#issuecomment-45229307
First website support using add.py :)

Closes #97

### CODE REVIEW

**Comment by jayvdb** [comment]
Aww .. it didnt pass ;( ;)

**Comment by seeeturtle** [comment]
Yeah, it's prototype for now...
I'm fixing now :)

**Comment by seeeturtle** [comment]
yup, it's fixed.
the coala error will be fixed after 22a4c2d

**Comment by seeeturtle** [comment]
@jayvdb, done :)

**Pull request merged**
