### PR TITLE
Add validation to form. Fixes #7.

### LINKED ISSUE #7: App doesnt work when given a name with special characters
1. When given a name with slash in between, The app keeps loading on forever
2. When given a name with # in between , the app only considers the letters before # for checking the    availability.
3. Some sites do not allow the names with special characters. So appropriate arrangement should be made within the software.

### PR DESCRIPTION
**Pull request by Asuza**
- Updated the form to use HTML5 form validation
- Added a message explaining which characters you can type

### CODE REVIEW

**Comment by manu-chroma** [comment]
Hey @Asuza, thanks for the PR! 

I will get back to you by the weekend. :D

**Comment by manu-chroma** [comment]
Hey, hyphens should also be allowed. 
Also, in the tip: rather than writing the complete names you can specify the special char symbols.

**Comment by Asuza** [comment]
@manu-chroma, I updated it. Let me know if anything else needs changed.

**Comment by manu-chroma** [comment]
LGTM! Thanks alot @Asuza

**Pull request merged**
